version: '3.7'
services:
  db:
    image: bagiasn/postgres:1.0
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "******"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"

  redis:
    image: bagiasn/redis:1.0
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"

  user-api:
    image: bagiasn/user-api:1.0
    container_name: user
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/users
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=!QL5S7BDFRs8
      - SPRING_REDIS_HOST=redis
    ports:
      - "8100:8100"
    depends_on:
      - db

  catalog-api:
    image: bagiasn/catalog-api:1.0
    container_name: catalog
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/catalog
      - SPRING_DATASOURCE_USERNAME=dev
      - SPRING_DATASOURCE_PASSWORD=!QL5S7BDFRs8
    ports:
      - "8090:8090"
    depends_on:
      - db

  gateway-api:
    image: bagiasn/gateway-api:1.0
    container_name: gateway
    environment:
      - ZUUL_ROUTES_CATALOG_URL=http://catalog-api:8090/catalog
      - ZUUL_ROUTES_USER_URL=http://user-api:8100/user
    ports:
      - "8080:8080"
    depends_on:
      - catalog-api
      - user-api

  announcement-server:
    image: bagiasn/announcement-server:1.0
    container_name: announcement-server
    ports:
      - "12000:12000"

  announcement-publisher:
    image: bagiasn/announcement-publisher:1.0
    container_name: announcement-publisher
    ports:
      - "8585:8585"
    depends_on:
      - announcement-server