version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "******"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:5.0.7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"