version: '3.7'
services:
  db:
    image: "postgres:12.0-alpine"
    environment:
      POSTGRES_PASSWORD: "******"
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data

volumes:
  db-data: