version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "******"
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres/init:/docker-entrypoint-initdb.d