version: '3.7'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "******"
    ports:
      - "5432:5432"
    volumes: 
      - ./postgres/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:5.0.7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    container_name: rabbitmq
    ports:
    - "5672:5672"
    - "15672:15672"